# Generated by Django 4.2.7 on 2025-10-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategory',
            name='is_menu',
            field=models.BooleanField(default=True),
        ),
    ]
