# Generated by Django 4.2.7 on 2025-10-14 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventdate_created_at_eventdate_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='is_registered',
            new_name='need_registration',
        ),
        migrations.AddField(
            model_name='event',
            name='event_dates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='EventDate',
        ),
    ]
