# Generated by Django 4.2.7 on 2025-10-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_is_registered_event_need_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='from_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='to_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_dates',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
