# Generated by Django 5.2.4 on 2025-07-19 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationcategory',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='donationsubcategory',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
