# Generated by Django 5.2.4 on 2025-07-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_alter_donationcategory_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='donationsubcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
