# Generated by Django 4.2.7 on 2025-09-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_alter_donationcategory_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationsubcategory',
            name='title',
            field=models.CharField(error_messages={'unique': 'Donation Sub Category already exists.'}, max_length=250, unique=True),
        ),
    ]
